[build-system]
requires = [
'setuptools>=42',
'cloudpickle==2.2.1',
'contourpy==1.1.0',
'cycler==0.11.0',
'Farama-Notifications==0.0.4',
'filelock==3.12.2',
'fonttools==4.42.0',
'gym==0.26.2',
'gym-notices==0.0.8',
'gymnasium==0.28.1',
'jax-jumpy==1.0.0',
'Jinja2==3.1.2',
'kiwisolver==1.4.4',
'lenses==1.1.0',
'MarkupSafe==2.1.3',
'matplotlib==3.7.2',
'mpmath==1.3.0',
'networkx==3.1',
'numpy==1.25.2',
'packaging==23.1',
'pandas==2.0.3',
'Pillow==10.0.0',
'pyparsing==3.0.9',
'python-dateutil==2.8.2',
'pytz==2023.3',
'scipy==1.11.1',
'six==1.16.0',
'stable-baselines3==2.0.0',
'sympy==1.12',
'torch==2.0.1',
'typing_extensions==4.7.1',
'tzdata==2023.3'

]
build-backend = 'setuptools.build_meta'