[tool.poetry]
name = "trad"
version = "0.1.3"
description = "Composable Radiative Transfer"
authors = ["Chi-kwan Chan <chanc@arizona.edu>"]
readme = "README.rst"
packages = [{include="trad", from="mod"}]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22"
astropy = "^5.0"
phun = "^0.1.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^4.4.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
