[tool.poetry]
name = "citation_utils"
version = "0.4.9"
description = "Pattern matching Philippine Supreme Court citations."
authors = ["Marcelino G. Veloso III <contact@mv3.dev>"]
homepage = "https://lawsql.com"
repository = "https://github.com/justmars/citation-utils"
documentation = "https://justmars.github.io/citation-utils"
classifiers = [
  "Topic :: Text Processing :: General",
  "Programming Language :: Python :: 3.11",
  "Typing :: Typed",
  "Development Status :: 4 - Beta",
  "Intended Audience :: Legal Industry",
  "Framework :: Pydantic",
  "Framework :: Pytest",
]

[tool.poetry.dependencies]
python = "^3.11"
citation_report = "^0.1.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3"
pytest-cov = "^2.12.1"
pre-commit = "^3.3"
mkdocs = "^1.4.3"
mkdocstrings = {extras = ["python"], version = "^0.22.0"}
mkdocs-material = "^9.1.16"
ipykernel = "^6.23.2"

[tool.pytest.ini_options]
minversion = "7.3"
addopts = "-ra -q --doctest-modules --cov"
filterwarnings = [
  "ignore::DeprecationWarning", # DeprecationWarning: pkg_resources is deprecated as an API
]
testpaths = ["tests", "citation_utils"]

[tool.ruff]
ignore = ["F401", "F403"]
fixable = ["F", "E", "W", "I001"]
select = ["F", "E", "W", "I001"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
