[build-system] 
requires = ["hatchling"] 
build-backend = "hatchling.build"

[project] 
name = "mrfix"
version = "2.0.15"
authors = [   
  { name="Valerii Zhuravlev", email="valerzhurav2011@gmail.com" },
] 
description = "A package with a set of decorator-methods for automatic testing of the user interface using Python + Selenium"
readme = "README.md" 
requires-python = ">=3.9"
classifiers = [     
  "Programming Language :: Python :: 3",     
  "License :: OSI Approved :: MIT License",     
  "Operating System :: OS Independent", 
]  
[project.urls] 
"Homepage" = "https://github.com/MrFix-Autotesting-Framework" 


