[tool.poetry]
name = "shapes-recognition"
version = "3.1.3"
description = "\"shapes-recognition\" is a New Recognition Technology"
authors = ["Boris Kravtsov <kravtsov.development@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "shapes_recognition"}]

[tool.poetry.dependencies]
python = "^3.10"
opencv-python-headless = "^4.8.0.74"
tqdm = "^4.65.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
