# SPDX-FileCopyrightText: Copyright (c) 2023 Jose D. Montoya
#
# SPDX-License-Identifier: MIT

[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]

[project]
name = "micropython-bmp581"
description = "MicroPython Driver for the Bosch BMP581 pressure sensor"
version = "0.1.3"
readme = "README.rst"
authors = [{ name = "JDM", email = "xxyx@mailmeto.mozmail.com" }]
urls = { Homepage = "https://github.com/jposada202020/MicroPython_BMP581" }
keywords = [
    "sensor",
    "micropython",
    "pressure",
    "bosch",
    "bmp581",
    "altitude",
    "temperature",
]
license = { text = "MIT" }
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Hardware",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: Implementation :: MicroPython",
]
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools]
packages = ["micropython_bmp581"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
