[tool.poetry]
name = "get-pwbrowser-sync"
version = "0.1.3"
description = "Instantiate a playwright chromium (sync as opposed to async) browser"
authors = ["ffreemt"]
readme = "README.md"
repository = "https://github.com/ffreemt/get-pwbrowser-sync"

[tool.poetry.dependencies]
python = "^3.7"
logzero = "^1.6.3"
playwright = {extras = ["chromium"], version = "^1.24.0"}
pydantic = {extras = ["dotenv"], version = "^1.8.1"}
pyquery = "^1.4.3"
typing-extensions = "4.7.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.21.0"
linetimer = "^0.1.4"
chardet = "^4.0.0"
flake8 = "^3.9.0"
pytest-playwright = "^0.0.12"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
# Uncomment this if your project is hosted on GitHub:
# github_url = "https://github.com/<user or organization>/<project>/"
