[tool.poetry]
name = "cloudsdp"
version = "0.1.0"
description = ""
authors = ["Naveen Anil <naveenms01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
google-cloud-bigquery = "^3.11.4"
google-cloud-run = "^0.9.1"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
