image: python:3.9-slim-bullseye

default:
  tags:
    - atc-runner
    - docker

before_script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt -y install make git curl jq
  - make install_build_deps

stages:
  - lint
  - build
  - dist

lint:
  stage: lint
  script:
    - make lint
  except:
    - tags
  
build:
  artifacts:
    paths:
      - dist/
  stage: build
  script:
    - make build
  except:
    - tags

dist:
  stage: dist
  script:
    - make DIST_PASSWORD="$PYPI_TOKEN" dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE  =~ /Merge Ref.*/
tag:
  stage: dist
  script:
    - make DIST_PASSWORD="$TAG_TOKEN" tag
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE  =~ /Merge Ref.*/
