[build-system]
requires = ["setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "scidmcli"
authors = [
    {name = "WeiYu", email = "wychen@narlabs.org.tw"},
]
version = "0.0.2dev"
description = "NCHC SciDM"
readme = "README.rst"
requires-python = ">=3.6"
keywords = ["ckan"]
license = {text = "apache2"}
classifiers = [
    "Topic :: Database :: Front-Ends",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "ckanapi",
    "requests",
    "os",
    "configparser"
]

[project.scripts]
my-script = "scidmcli:main"

