[tool.poetry]
name = "orbit-component-dbshell"
version = "1.0.8"
description = "Orbit Database shell component"
authors = ["Gareth Bult <gareth@madpenguin.uk>"]
license = "MIT"
readme = "README.md"
include = ['README.md', 'LICENSE.md']
packages = [{include = "orbit_component_dbshell"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Database :: Database Engines/Servers",
    "Intended Audience :: Developers",
]
homepage = "https://gitlab.com/madpenguin/orbit-component-dbshell"
repository = "https://gitlab.com/madpenguin/orbit-component-dbshell"
documentation = "https://gitlab.com/madpenguin/orbit-component-dbshell"

[project.urls]
"Homepage" = "https://gitlab.com/madpenguin/orbit-component-dbshell"
"Bug Tracker" = "https://gitlab.com/madpenguin/orbit-component-dbshell/-/issues"

[tool.poetry.dependencies]
python = ">=3.10"
orbit-database-shell = "^1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
