# SPDX-FileCopyrightText: Copyright (c) 2023 Jose D. Montoya
#
# SPDX-License-Identifier: MIT

[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]

[project]
name = "micropython-dps310"
description = "MicroPython Driver for the DPS310 sensor"
version = "0.1.3"
readme = "README.rst"
authors = [{ name = "Jose D. Montoya", email = "dps310@mailmeto.mozmail.com" }]
urls = { Homepage = "https://github.com/jposada202020/MicroPython_dps310" }
keywords = [
    "micropython",
    "DPS310",
    "sensor",
    "temperature",
    "pressure",
    "altitude",
]
license = { text = "MIT" }
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Hardware",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: Implementation :: MicroPython",
]
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools]
packages = ["micropython_dps310"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
