[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "lost_cat_images"
version = "1.1.0"
authors = [
  { name="Dreffed aka David Gloyn-Cox", email="dreffed@gmail.com" },
  { name="Thoughtswin Systems Inc", email="david.gloyn-cox@thoughtswinsystems.com" },
]
description = "Lost Cat (images) is a package for image related uris and tools"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "lost_cat>=0.1.6",
    "lost_cat_office",
    "numpy",
    "opencv-python",
    "pandas",
    "pillow",
    "psutil",
    "pymupdf",
    "pytesseract",
    "python-dotenv",
    "scipy",
    "scikit-image",
    "xlsxwriter",
    "openpyxl"
]

[tool.setuptools.packages.find]
include = ["lost_cat_images*"]

[project.urls]
"Homepage" = "https://github.com/thoughtswinsystems/lost_cat_images"
"Bug Tracker" = "https://github.com/thoughtswinsystems/lost_cat_images/issues"
