[tool.poetry]
name = "beam-sdk"
version = "0.14.10"
description = ""
authors = ["luke lombardi <luke@slai.io>"]
packages = [
    { include = "beam", from = "src" },
    { include = "beam/**/*.py", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
marshmallow = "3.18.0"
marshmallow-dataclass = "^8.5.9"
typeguard = "^2.13.3"
croniter = "^1.3.7"
Jinja2 = "^3.1.2"
validators = "^0.20.0"
importlib-metadata = "5.2.0"
astor = "^0.8.1"

[tool.poetry.dev-dependencies]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
black = "^22.8.0"
attrs = "^22.1.0"
docstring-parser = "^0.15"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
