[project]
name = "pdm-mina"
version = "0.3.1"
dependencies = [
    "pdm>=2.5.0",
    "mina-build>=0.2.1",
    "tomli>=1.1.0; python_version < \"3.11\"",
]
requires-python = ">=3.9"
readme = "README.md"

[project.license]
text = "MIT"

[project.entry-points.pdm]
mina = "mina.plugin:ensure_pdm"

[tool.pdm.dev-dependencies]
dev = [
    "black>=22.3.0",
    "isort>=5.10.1",
    "devtools>=0.8.0",
]

[tool.pdm.build]
includes = [
    "mina",
]
excludes = [
    "mina/backend",
]

[tool.mina]
enabled = true
override-global = false

[tool.mina.packages.backend]
override = false
includes = [
    "mina/backend",
]
raw-dependencies = []

[tool.mina.packages.backend.project]
name = "mina-build"
version = "0.5.1"
description = "build backend for Mina Package Structure"
authors = [
    { name = "GreyElaina", email = "GreyElaina@outlook.com" },
]
dependencies = [
    "pdm-backend",
    "tomli",
    "editables",
]
requires-python = ">=3.9"
readme = "README.build.md"

[tool.mina.packages.backend.project.license]
text = "MIT"

[tool.mina.packages.cli-pdm]
includes = [
    "mina",
]
excludes = [
    "mina/backend",
]

[tool.mina.packages.cli-pdm.project]
name = "pdm-mina"
version = "0.3.1"
dependencies = [
    "pdm>=2.5.0",
    "mina-build>=0.2.1",
    "tomli>=1.1.0; python_version < \"3.11\"",
]
requires-python = ">=3.9"
readme = "README.md"

[tool.mina.packages.cli-pdm.project.license]
text = "MIT"

[tool.mina.packages.cli-pdm.project.entry-points.pdm]
mina = "mina.plugin:ensure_pdm"

[build-system]
requires = [
    "mina-build>=0.2.6",
    "editables",
]
build-backend = "mina.backend"
