[tool.poetry]
name = "aws-plugin-bucket-policy"
version = "1.0.0"
description = "awscli S3 bucket-policy plugin"
authors = ["Tomas Hlava <hlava@cesnet.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry>=1.3"]
build-backend = "poetry.masonry.api"
