[tool.poetry]
name = "linkedin-auto-scraper"
version = "0.2.1"
description = "A tool to scrape infomation of people in a particular based on their job title and location"
authors = ["kenfelix <Kmrapper.kf@gmail.com>"]
readme = "README.md"
packages = [{include = "linkedin_auto_scraper"}]

[tool.poetry.scripts]
linkedin-auto-scraper = "linkedin_auto_scraper.main:app"

[tool.poetry.dependencies]
python = "^3.10"
about-time = "^4.2.1"
alive-progress = "^3.1.4"
async-generator = "^1.10"
attrs = "^23.1.0"
black = "^23.7.0"
certifi = "^2023.7.22"
charset-normalizer = "^3.2.0"
click = "^8.1.6"
colorama = "^0.4.6"
commonmark = "^0.9.1"
exceptiongroup = "^1.1.2"
fake-useragent = "^1.2.1"
grapheme = "^0.6.0"
h11 = "^0.14.0"
idna = "^3.4"
isort = "^5.12.0"
mypy-extensions = "^1.0.0"
numpy = "^1.25.2"
outcome = "^1.2.0"
packaging = "^23.1"
pandas = "^2.0.3"
pathspec = "^0.11.2"
platformdirs = "^3.10.0"
pydantic = "^2.1.1"
pygments = "^2.16.1"
pysocks = "^1.7.1"
python-dateutil = "^2.8.2"
python-dotenv = "^1.0.0"
pytz = "^2023.3"
requests = "^2.31.0"
selenium = "^4.11.2"
shellingham = "^1.5.0.post1"
six = "^1.16.0"
sniffio = "^1.3.0"
sortedcontainers = "^2.4.0"
tomli = "^2.0.1"
tqdm = "^4.66.0"
trio = "^0.22.2"
trio-websocket = "^0.10.3"
typer = "^0.9.0"
typing-extensions = "^4.7.1"
urllib3 = "^2.0.4"
webdriver-manager = "^4.0.0"
wsproto = "^1.2.0"
xlsxwriter = "^3.1.2"
rich = "^13.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
