[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ladderbot"
version = "0.0.18"
authors = [
  { name="ch7cken", email="ch7cken@proton.me" },
]
description = "game automation"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "undetected-chromedriver==3.5.0",
]
[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"

[project.scripts]
ladderbot = "ladderbot:run.bot"

[tool.setuptools.packages.find]
where = ["src"]