[build-system]
requires = ["hatchling", "jax", "jaxopt >= 0.6", "typing-extensions >= 4.5.0","wandb >= 0.14.2","pandas == 1.5.3","plotly >= 5.14.1","flax >= 0.6.10","tensorflow_datasets"]
build-backend = "hatchling.build"

[project]
dependencies = ["hatchling", "jax", "jaxopt >= 0.6", "typing-extensions >= 4.5.0", "wandb >= 0.14.2", "pandas == 1.5.3", "plotly >= 5.14.1", "flax >= 0.6.10", "tensorflow_datasets"]
name = "benchmarx"
version = "0.1.0"
authors = [
  { name="Salex", email="31salex31@gmail.com" },
]
description = "Tools for benchmarking optimization methods"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/AlexToW/benchmarx"
"Bug Tracker" = "https://github.com/AlexToW/benchmarx/issues"