[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tablate"
version = "0.0.62"
authors = [
  { name="Guy de Winton", email="guy@codehippie.io" },
]
description = "A highly customizable and dynamic table renderer for IPython & CLI applications."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.com/guydewinton/tablate"
"Bug Tracker" = "https://gitlab.com/guydewinton/tablate/issues"