[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "survey-report-generator"
version = "0.0.13"
description = "A tool to generate survey reports from collected data"
authors = ["Oliver Hahn <oliver.a.hahn@gmail.com>"]
license = "MIT"  # Assuming your project is MIT licensed based on the classifiers
readme = "README.md"
homepage = "https://github.com/nsw-wildlife-drone-hub/report-generator"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["survey_report_generator/report-template.docx", "survey_report_generator/storage.json"]

[tool.poetry.dependencies]
python = ">=3.7"
gdown = "^4.7.1"
oauth2client = "^4.1.3"
httplib2 = "^0.22.0"
pandas = "^2.0.1"
docxtpl = "^0.11.5"
numpy = "^1.24.3"
geopandas = "^0.9.0"
contextily = "^1.3.0"
shapely = "^2.0.1"
google-api-python-client = "^2.86.0"
fiona = "*"

