[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "relative_chemical_space"
version = "0.0.5"
authors = [
  { name="Stiv Llenga", email="stiv.llenga@h-its.org" },
]
description = "Functions for generating the MFSR and RCS representations."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/hits-ccc/MFSR_RCSa"
