[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aws_hexagonal_adapters"
description = "Adapters following hexagonal architecture to connect various AWS services."
version = "1.1.1"
authors = [{name = "Tomasz Szuster", email = "tomasz.szuster@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
        "boto3>=1.26.71,<2.0.0",
        "botocore>=1.29.71,<2.0.0",
        "aws_lambda_powertools>=2.8.0,<4.0.0",
]
[project.urls]
Home = "https://github.com/airmonitor/aws-hexagonal-adapters"
Bug_Tracker = "https://github.com/airmonitor/aws-hexagonal-adapters/issues"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/.gitignore",
  "/.idea",
  "/.pre-commit-config.yaml",
  "/pyproject.toml",
  "/requirements.txt",
  "/setup.cfg",
]
