[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'

[project]
name = "MyOverlay"
version = "0.3.0"
authors = [
  { name="Erik Reimann", email="erikreimann28@gmail.com" },
]
description = "Customized Text Only Screen Overlay"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "win32api",
  "pygame",
  "win32con",
  "win32gui",
  "ctypes",
  "thefuzz",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/HerpesHabenderHauptmannHarry/MyOverlay"
"Bug Tracker" = "https://github.com/HerpesHabenderHauptmannHarry/MyOverlay/issues"