{% if cookiecutter.packaging_provider == 'flit' -%}
[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=2,<4"]

[tool.flit.metadata]
author = "{{cookiecutter.author}}"
author-email = "{{cookiecutter.author_email}}"
description-file = "README.rst"
home-page = "{{cookiecutter.project_url}}"
module = "{{cookiecutter.project_slug}}"


[tool.flit.metadata.requires-extra]
dev = [
{%- if ('disable_bh_dependencies' not in cookiecutter) or (not cookiecutter.disable_bh_dependencies) %}
    "build_harness {{cookiecutter.build_harness_version}}",
{%- endif %}
    "pre_commit >=2.13.0, <3",
]
doc = [
    "sphinx >=4.5.0, <5",
    "sphinx_rtd_theme >=1.0, <2",
]
test = [
    "pytest >=7.1.1, <8",
    "pytest-cov >=3.0, <4",
    "pytest-mock >=3.6.1, <4",
]
{%- endif %}


[tool.black]
# Don't forget to sync this with isort, .flake8
line-length = {{cookiecutter.line_length}}


[tool.isort]
# Don't forget to sync this with black, .flake8
line_length = {{cookiecutter.line_length}}
profile = "black"


[tool.coverage.run]
# branch and concurrency settings seem to be needed due to this problem:
# pytest-cov internal error "Can't combine line data with arc data"
# https://github.com/pytest-dev/pytest-cov/issues/243
branch = true
concurrency = ["multiprocessing"]
omit = ["{{cookiecutter.project_slug}}/.venv/*"]
source = ["{{cookiecutter.project_slug}}"]


[tool.coverage.report]
exclude_lines = [
    "except ImportError",
    "raise NotImplementedError",
    "pass",
    "ABCmeta",
    "abstractmethod",
    "warnings.warn",
]
fail_under = {{ cookiecutter.coverage_threshold }}
precision = 0
show_missing = true
