[tool.poetry]
name = "pybrownomics"
version = "0.2.2"
description = ""
authors = ["Lorenzo Alencar Tomaz <lolo.tomaz@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "pybrownomics", from = "." }]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.12"
numpy = "^1.24.2"
matplotlib = "^3.7.2"
scipy = "^1.10.1"
pandas = "^2.0.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-mock = "^3.11.1"
black = "^23.7.0"
isort = "^5.12.0"
mypy = "^1.4.1"
click = "^8.1.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
