[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "typesense-server-wrapper-alpha"
description = "Python wrapper for Typesense Server"
authors = [
    {"name" = "Grant Jenks", "email" = "contact@grantjenks.com"},
]
readme = "README.rst"
requires-python = ">=3.7"
keywords = ["search", "typesense"]
license = {"text" = "Apache 2.0"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://grantjenks.com/docs/python-typesense-server-wrapper/"
Funding = "https://gum.co/python-typesense-server-wrapper"
Source = "https://github.com/grantjenks/python-typesense-server-wrapper"
Tracker = "https://github.com/grantjenks/python-typesense-server-wrapper/issues"

[tool.setuptools.dynamic]
version = {attr = "typesense_server_wrapper_alpha.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
