[tool.poetry]
name = "apix-core"
version = "0.0.9"
description = "apiX - The Python framework to create MongoDB-backed applications with GraphQL API web interface."
authors = ["Danijel Kivaranovic <dan@apix.org>"]
license = "MIT"
readme = "README.md"
keywords = ["graphql", "mongodb", "api", "starlette", "async"]
homepage = "https://apix.org"
repository = "https://github.com/ApixOrg/apix"
documentation = "https://apix.org"
packages = [
    { include = "apix", from = "." }
]

[tool.poetry.dependencies]
python = "^3.11"
starlette = "^0.26.1"
pymongo = "^4.3.3"
motor = "^3.1.1"
graphql-core = "^3.2.3"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"


[tool.poetry.extras]
uvicorn = ["uvicorn"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
