[build-system]
requires = [
  "setuptools",
  "Pillow",
  "numpy",
  "pandas",
]

[project]
name = "image2layout_computer_vision"
version = "0.1.7"
authors = [
  { name="Felix Do", email="felix.do.1030@gmail.com" },
]
description = "image processing and stuff"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/felix-do-wizardry/image2layout-computer-vision"
"Bug Tracker" = "https://github.com/felix-do-wizardry/image2layout-computer-vision"