[package]
name = "jlogr"
version = "0.1.209"
edition = "2021"
exclude = ["/tests"]
authors = ["Jesse Williams"]
url = "https://github.com/jesses-code-adventures/jlogr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
lib = "jlogr"
name = "jlogr"
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.72"
chrono = "0.4.26"
pyo3 = { version = "0.19.2", features = ["extension-module", "abi3-py39", "chrono", "anyhow"]}
termcolor = "1.2.0"


