[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "messaging-arbihacker"
version = "0.1.8"
authors = [
    { name = "Sergei Aslamazov", email = "mrvisioo@gmail.com" },
]
description = "Messaging utils"
readme = "README.MD"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "celery~=5.3.1",
    "kombu~=5.3.1",
]
[project.urls]
"Homepage" = "https://github.com/ArbiHacker/messaging-arbihacker"
