[tool.poetry]
name = "spline-agent"
version = "0.1.2"
description = "Spline agent for Python. Lineage tracking utility."
authors = ["Oleksandr Vayda <oleksandr.vayda@absa.africa>"]
license = "Apache-2.0"
homepage = "https://github.com/AbsaOSS/spline-python-agent"
repository = "https://github.com/AbsaOSS/spline-python-agent"
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
http-constants = "^0.5.0"
dynaconf = "^3.2.0"

[tool.poetry.group.dev.dependencies]
types-requests = "^2.31.0.2"
pytest = "^7.4.0"
mypy = "^1.4.1"

[build-system]
requires = ["poetry-core>=1.6.1"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "src"
log_cli = true
log_cli_level = "INFO"

[tool.mypy]
files = "."
check_untyped_defs = true
disable_error_code = ["type-abstract"]

[[tool.mypy.overrides]]
module = "http_constants.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
# this should be fixed in Dynaconf ver 4.0.0. See https://github.com/dynaconf/dynaconf/issues/448
module = "dynaconf.*"
ignore_missing_imports = true
