[tool.poetry]
name = "edu_segmentation"
version = "v0.0.110"
description = "To improve EDU segmentation performance using Segbot. As Segbot has an encoder-decoder model architecture, we can replace bidirectional GRU encoder with generative pretraining models such as BART and T5. Evaluate the new model using the RST dataset by using few-shot based settings (e.g. 100 examples) to train the model, instead of using the full dataset."
authors = ["Your Name <you@example.com>"]
readme = "readme.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.9"
attrs = "==23.1.0"
bleach = "==6.0.0"
build = "==0.10.0"
CacheControl = "==0.12.11"
certifi = "==2022.12.7"
charset-normalizer = "==3.1.0"
cleo = "==2.0.1"
click = "==8.1.3"
colorama = "==0.4.6"
crashtest = "==0.4.1"
distlib = "==0.3.6"
docutils = "==0.19"
dulwich = "==0.21.3"
filelock = "==3.12.0"
fsspec = "==2023.4.0"
html5lib = "==1.1"
huggingface-hub = "==0.14.1"
idna = "==3.4"
importlib-metadata = "==6.6.0"
installer = "==0.7.0"
Jinja2 = "==3.1.2"
joblib = "==1.2.0"
jsonschema = "==4.17.3"
keyring = "==23.13.1"
lockfile = "==0.12.2"
markdown-it-py = "==2.2.0"
MarkupSafe = "==2.1.2"
mdurl = "==0.1.2"
more-itertools = "==9.1.0"
mpmath = "==1.3.0"
msgpack = "==1.0.5"
networkx = "==3.1"
nltk = "==3.8.1"
numpy = "==1.24.3"
packaging = "==23.1"
pexpect = "==4.8.0"
pkginfo = "==1.9.6"
platformdirs = "==2.6.2"
poetry = "==1.4.2"
poetry-core = "==1.5.2"
poetry-plugin-export = "==1.3.1"
ptyprocess = "==0.7.0"
Pygments = "==2.15.1"
pyproject_hooks = "==1.0.0"
pyrsistent = "==0.19.3"
pywin32-ctypes = "==0.2.0"
PyYAML = "==6.0"
rapidfuzz = "==2.15.1"
readme-renderer = "==37.3"
regex = "==2023.3.23"
requests = "==2.29.0"
requests-toolbelt = "==0.10.1"
rfc3986 = "==2.0.0"
rich = "==13.3.5"
shellingham = "==1.5.0.post1"
six = "==1.16.0"
sympy = "==1.11.1"
tokenizers = "==0.13.3"
tomlkit = "==0.11.8"
torch = "==2.0.0"
tqdm = "==4.65.0"
transformers = "==4.28.1"
trove-classifiers = "==2023.4.25"
twine = "==4.0.2"
typing_extensions = "==4.5.0"
urllib3 = "==1.26.15"
virtualenv = ">20.4.5"
webencodings = "==0.5.1"
zipp = "==3.15.0"