[package]
name = "ast-grep-config"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]

authors= ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition= "2021"
license= "MIT"
repository= "https://github.com/ast-grep/ast-grep"
rust-version= "1.63"
version= "0.11.0"

[features]
default = ["regex"]

[dependencies]
ast-grep-core.path = "../ast-grep-core"

anyhow = "1.0"
bit-set= { version = "0.5.3" }
globset = "0.4.13"
regex = { version = "1.9.3" , optional = true }
serde= { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.25"
thiserror= "1.0.44"
