[metadata]
name = "turborest"
version = "0.1.5"
description = "A library for monitoring files and directories for changes"
long_description = """
A library for monitoring files and directories for changes
"""
license = "MIT"
author = "ByteSentinel.io"
author-email = "dev@bytesentinel.io"
url = "https://github.com/bytesentinel-io/turborest"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[options]
python_requires = ">=3.7"
package_dir = "src"
include_package_data = true

[options.packages.find]
where = "src"