[tool.poetry]
name = "hydev"
version = "1.3.2"
description = "Common tooling and configuration for pythonic development"
authors = ["hoverhell <hoverhell@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
hydautoflake = "hydev.main:Autoflake.run_cli"
hydblack = "hydev.main:Black.run_cli"
hyddeploy = "hydev.deploy:DeployManager.run_cli"
hydflake8 = "hydev.main:Flake8.run_cli"
hydfmt = "hydev.main:Format.run_cli"
hydisort = "hydev.main:ISort.run_cli"
hyd = "hydev.main:Fulltest.run_cli"
hydmypy = "hydev.main:Mypy.run_cli"
hydpytest = "hydev.main:Pytest.run_cli"
hydtest = "hydev.main:Fulltest.run_cli"

[tool.poetry.dependencies]
python = "^3.10"
# Libs
click = "^8.1.3"
pyyaml = "^6.0"
toml = "^0.10.2"
# Tooling
poetry = "^1.4.2"
pre-commit = "^3.2.2"
# Debug conveniences
coloredlogs = "^15.0.1"
ipdb = "^0.13.13"
# Formatting
autoflake = "^1.7.8"
black = "^23.3.0"
isort = "^5.12.0"
# `flake8`
flake8 = "^5.0.4"
flake8-broken-line = "^0.6.0"
flake8-debugger = "^4.1.2"
flake8-mock-x2 = "^0.4.1"
flake8-print = "^5.0.0"
flake8-pytest-style = "^1.7.2"
flake8-use-fstring = "^1.4"
# `mypy`
mypy = "^1.2.0"
# `pytest`
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"
pytest-blockage = "^0.2.4"
pytest-cov = "^4.0.0"
pytest-deadfixtures = "^2.2.1"
pytest-env = "^0.8.1"
pytest-timeout = "^2.1.0"
# `django`
django-coverage-plugin = {version = "^3.0.0", optional = true}
django-debug-toolbar = {version = "^4.0.0", optional = true}
django-extra-checks = {version = "^0.13.3", optional = true}
django-migration-linter = {version = "^4.1.0", optional = true}
django-querycount = {version = "^0.8.3", optional = true}
django-split-settings = {version = "^1.2.0", optional = true}
django-stubs = {version = "^1.16.0", optional = true}
django-stubs-ext = {version = "^0.8.0", optional = true}
django-test-migrations = {version = "^1.2.0", optional = true}
flake8-django = {version = "^1.2", optional = true}
pytest-django = {version = "^4.5.2", optional = true}
# ...
poetry-plugin-up = "^0.3.0"

[tool.poetry.extras]
django = [
  "django-coverage-plugin",
  "django-debug-toolbar",
  "django-extra-checks",
  "django-migration-linter",
  "django-querycount",
  "django-split-settings",
  "django-stubs",
  "django-stubs-ext",
  "django-test-migrations",
  "flake8-django",
  "pytest-django",
]

[tool.poetry.group.dev.dependencies]
types-toml = "^0.10.8.5"
types-requests = "^2.28.11.15"
types-pyyaml = "^6.0.12.8"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
