[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seiketsu-api"
version = "1.0.8"
authors = [
  { name="LoLip_p", email="mr.timon51@gmail.com" },
]
description = "A Python library to interact with a chat API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
