[project]
name = "stdf-tamer"
description = "a stdf reader/writer/analyser/converter and robotframework library"
dynamic = []
authors = [
    { name = "Labor DC jona", email = "" },
    { name = "Franz Haas", email = "franz.haas@ams-osram.com" },
]
dependencies = [
    "robotframework",
    "construct",
    "docopt",
    "rich",
    "polars",
    "XlsxWriter",
    "xlsx2csv>=0.8.1",
]
requires-python = ">=3.8.0"
readme = "README.md"
keywords = [
    "STDF",
    "ATE",
]
version = "1.0.6"

[project.license]
text = "apache 2.0"

[project.urls]
Homepage = "https://gittf.ams-osram.info/labor-rapperswil-jona/ams-tamer"
Repository = "https://gittf.ams-osram.info/labor-rapperswil-jona/ams-tamer"

[project.scripts]
stdfconvert = "converter:main"
stdfrerunwithnewlimits = "simulator:main"
stdfanalyse = "stdfanalyser:main"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
source = [
    { url = "https://pypi.org/simple", verify_ssl = true, name = "pypi" },
]

[tool.pdm.version]
source = "scm"

[tool.pdm.dev-dependencies]
dev = [
    "pdoc>=12.3.0",
    "ipython>=8.6.0",
    "radon>=5.1.0",
]
