[project]
name = "tortoise-api"
requires-python = ">=3.9"
authors = [
    {name = "Artemiev", email = "mixartemev@gmail.com"},
]
keywords = ["starlette", "fastapi", "admin", "generator", "db-model", "crud", "tortoise-orm", "ASGI-admin"]
description = "Simplest fastest minimal REST API CRUD generator for Tortoise ORM models"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "asyncpg",
    "python-dotenv",
    "starlette",
    "tortoise-api-model>=0.2.3",
    "uvicorn"
]
version = "0.2.8"

[project.urls]
Homepage = "https://github.com/mixartemev/tortoise-api"
Repository = "https://github.com/mixartemev/tortoise-api"

[tool.setuptools]
packages = ["tortoise_api"]
