[tool.poetry]
name = "mechanical-bull"
version = "0.2.1"
description = "A framework to automate reacting to ActivityStreams events."
authors = ["Helge <helge.krueger@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "mechanical_bull"}]
repository = "https://codeberg.org/bovine/mechanical_bull"
documentation = "https://mechanical-bull.readthedocs.io/en/latest/"

[tool.poetry.dependencies]
python = "^3.11"
tomli-w = "^1.0.0"
bovine = "^0.3.0"
sphinx-argparse = "^0.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"
black = "^23.1.0"
ruff = "^0.0.261"


[tool.poetry.group.docs.dependencies]
sphinx = "^6.1.3"
sphinx-rtd-theme = "^1.2.0"
sphinxcontrib-napoleon = "^0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
asyncio_mode="auto"
log_cli= 1
log_cli_level="info"