[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "teapots-teal"
version = "0.2"
description = "Teacups Listener for ping, push and callback events"
readme = "README.rst"
homepage = "https://teal.teapots.fr/"
repository = "https://gitea.teapots.fr/teapots/teal"
documentation = "https://teal.teapots.fr/"
packages = [
    { include = "teal" },
]
authors = ["Thomas Touhey <thomas@touhey.fr>"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Communications",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.10"
aio-pika = "^9.0.5"
fastapi = "^0.94.1"
gunicorn = "^20.1.0"
jinja2 = "^3.1.2"
pydantic = "^1.10.6"
redis = "^4.5.1"
uvicorn = "^0.21.1"
websockets = "^10.4"

[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
flake8-annotations = "^2.9.1"
flake8-bandit = "^4.1.1"
flake8-commas = "^2.1.0"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
flake8-no-implicit-concat = "^0.3.3"
flake8-quotes = "^3.3.2"
flake8-rst-docstrings = "^0.2.7"
flake8-use-fstring = "^1.4"
flake8-walrus = "^1.2.0"
httpx = "^0.24.1"  # Needed for FastAPI's test client.
mypy = "^1.1.1"
pytest = "*"
pytest-asyncio = "^0.20.3"
pytest-cov = "^4.0.0"
pytest-mock = "*"
pytest-rabbitmq = "^3.0.1"
pytest-redis = "^3.0.2"
responses = "*"
types-redis = "^4.5.1.5"

[tool.poetry.group.docs.dependencies]
furo = "^2023.3.27"
poetry = "^1.4.2"
sphinx = "^6.1.3"
sphinx-autobuild = "^2021.3.14"

[tool.pytest.ini_options]
addopts = '--cov=teal --cov-report html --cov-report term --doctest-modules'

[tool.mypy]
ignore_missing_imports = true
mypy_path = "."
warn_unused_ignores = true

[tool.coverage.report]
exclude_lines = [
    "@abstractmethod",
    "@_abstractmethod",
    "pragma: no cover"
]
