[tool.poetry]
name = "cpmax-toolbox"
version = "0.3.8"
description = ""
authors = ["JRoseCPMax <j.rose@cpmax.com>"]
readme = "README.md"
packages = [{include = "cpmax_toolbox"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
requests = "^2.28.2"
pytz = "^2022.7.1"
pandas = "^1.5.3"
scipy = "^1.10.1"
rich = "^13.3.1"
matplotlib = "^3.7.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
ipykernel = "^6.21.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
