[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "akriml"
authors = [
    {name = "Sabarish Vadarevu"},
    {email = "sabarish.vadarevu@akridata.ai"}
]
# We'll specify version statically
# dynamic = ["version"]
version = "0.0.3"
description = "ML methods for exploration and curation of large, high-dimensional datasets."
license = {file = "LICENSE"}
requires-python = ">=3.8"
classifiers = [
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
]
dependencies = [
    "cython>=0.29.32", "numpy>=1.19.2", "scikit-learn>=1.1.3", "scipy>=1.9.2"
]

[project.urls]
homepage = "https://akridata.ai"
repository = "https://github.com/akridata-ai/AkriML"

[project.optional-dependencies]
dev = ["flake8", "pre-commit", "pytest", "black", "mypy", "pylint", "doctest", "twine"]
test = ["pytest", "doctest"]

[tool.setuptools]
packages = ["akriml", "akriml.sketch"]
