[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.commitizen]
version = "0.3.1"
version_files = ["corallium/__init__.py:^__version", "pyproject.toml:^version"]

[tool.poetry]
authors = ["Kyle King <dev.act.kyle@gmail.com>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
] # https://pypi.org/classifiers/
description = "Shared functionality for the calcipy-ecosystem"
documentation = "https://corallium.kyleking.me"
include = ["LICENSE"]
keywords = []
license = "MIT"
maintainers = []
name = "corallium"
readme = "docs/README.md"
repository = "https://github.com/kyleking/corallium"
version = "0.3.1"

[tool.poetry.dependencies]
python = "^3.8.12"
beartype = ">=0.15.0"
pydantic = ">=1.10.4"
rich = ">=12.6.0"
tomli = {markers = "python_version < '3.11'", version = ">=2.0.1"}

[tool.poetry.group.dev.dependencies]
calcipy = {extras = ["doc", "lint", "nox", "stale", "tags", "test", "types"], version = ">=1.6.2"}
pytest-asyncio = ">=0.21.0"
pytest-structlog = ">=0.6" # Provides pytest fixture 'log'
pytest-subprocess = ">=1.4.1"
structlog = ">=22.3.0"
types-pyyaml = ">=6.0.12.8"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kyleking/corallium/issues"
"Changelog" = "https://github.com/kyleking/corallium/blob/main/docs/docs/CHANGELOG.md"

[tool.pyright]
include = ["corallium"]
pythonVersion = "3.8"
