name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Install rye
        uses: baptiste0928/cargo-install@v2
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main
      - name: Fix Python version
        run: rye pin 3.10
      - name: Install Dependencies
        run: rye sync
      - name: Run tests
        run: |
          rye run pytest
