[tool.poetry]
name = "climate-search-cli"
version = "0.1.3"
description = "A python program that can be run from the command line, and used to search climate policy documents."
authors = ["fred oloughlin <fred@oloughl.in>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "cs"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.6"
pandas = "^2.0.3"
sqlalchemy = "^2.0.19"
scikit-learn = "^1.3.0"
numpy = "1.24.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
pyright = "^1.1.321"
isort = "^5.12.0"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportMissingImports = false

[tool.poetry.scripts]
cs = "cs.cli:entrypoint"