[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    { name = "Team IO-Aero", email = "info@io-aero.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
description = "TBD"
keywords = [
    "TBD",
    "TBD",
]
maintainers = [
    { name = "Team IO-Aero", email = "info@io-aero.ch" },
]
name = "iotemplatelib"
readme = "README.md"
requires-python = ">=3.10"
version = "1.0.4"

[project.urls]
"Bug Tracker" = "https://github.com/io-aero/io-template-lib/issues"
"Documentation" = "https://io-aero.github.io/io-template-lib/"
"Homepage" = "https://github.com/io-aero/io-template-lib"
"Release History" = "https://io-aero.github.io/io-template-lib/release_history/"
"Release Notes" = "https://io-aero.github.io/io-template-lib/release_notes/"
"Source" = "https://github.com/io-aero/io-template-lib/iotemplatelib/"

[tool.bandit]

[tool.coverage.run]
omit = ["setup.py"]

[tool.isort]
float_to_top = true
force_single_line = true
overwrite_in_place = true
profile = "black"

[tool.pydocstyle]
match = '((?!test_).*\.py)'

[tool.pytest.ini_options]
console_output_style = "count"
log_cli_level = "INFO"
log_file = "logging_io-template-lib_pytest.log"
log_file_level = "DEBUG"
log_level = "DEBUG"
markers = ["issue"]
norecursedirs = "./tests/helpers"
pythonpath = "./iotemplatelib/"
testpaths = "./tests/"

[tool.setuptools]
packages = ["iotemplatelib"]

[tool.setuptools.package-data]
iotemplatelib = ["*.pyi", "py.typed"]
