# SPDX-FileCopyrightText: Copyright (c) 2023 Jose D. Montoya
#
# SPDX-License-Identifier: MIT

[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm",
]

[project]
name = "circuitpython-tmp117"
description = "CircuitPython TMP117 Temperature Sensor Low Memory driver"
version = "0.1.2"
readme = "README.rst"
authors = [
    {name = "JDM", email = "jdm@mozmail.com"}
]
urls = {Homepage = "https://github.com/jposada202020/CircuitPython_TMP117"}
keywords = [
    "sensor",
    "circuitpython",
    "tmp117",
    "temperature",
    "TMP117",
    "low",
    "memory",
    "sensor",
    "driver",
]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Hardware",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools]
py-modules = ["tmp117"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {optional = {file = ["optional_requirements.txt"]}}
