[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "investlib"
version = "0.0.6"
authors = [
  { name="Cellarosi Marco", email="cellarosi@gmail.com" },
]
description = "InvestLib is a Python package for backtesting ETF investments"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

dependencies = [
  "certifi==2023.5.7",
  "charset-normalizer==3.1.0",
  "freezegun==1.2.2",
  "idna==3.4",
  "numpy==1.24.4",
  "pandas==2.0.3",
  "python-dateutil==2.8.2",
  "pytz==2023.3",
  "requests==2.31.0",
  "six==1.16.0",
  "tzdata==2023.3",
  "urllib3==2.0.3",
  "plotly==5.15.0"
]

[project.urls]
"Homepage" = "https://github.com/cellarosi/investlib"
"Bug Tracker" = "https://github.com/cellarosi/investlib/issues"
