[tool.poetry]
name = "locatieserver"
version = "0.5.4"  # <<COOKIETEMPLE_FORCE_BUMP>>
description = "Locatieserver api client"
authors = ["Jelmer Draaijer <info@jelmert.nl>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/foarsitter/locatieserver"
repository = "https://github.com/foarsitter/locatieserver"
documentation = "https://locatieserver.readthedocs.io"
packages = [
    { include = "locatieserver" },
]
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]


[tool.poetry.dependencies]
python = "^3.7.1"
pydantic = "^1.8.2"
httpx = ">=0.23,<0.25"


[tool.poetry.dev-dependencies]
respx = "^0.20.1"
pytest = "^7.4.0"
coverage = {extras = ["toml"], version = "^7.1"}
safety = "^2.3.3"
mypy = "^0.991"
typeguard = "^2.13.3"
xdoctest = {extras = ["colors"], version = "^1.1.1"}
sphinx = "^5.1.1"
sphinx-autobuild = "^2021.3.14"
pre-commit = "^2.11.1"
flake8 = "^3.8.4"
black = "^22.3.0"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^23.1.20"
flake8-docstrings = "^1.5.0"
flake8-rst-docstrings = "^0.3.0"
pep8-naming = "^0.13.2"
reorder-python-imports = "^3.9.0"
pre-commit-hooks = "^4.4.0"




sphinx-rtd-theme = "^1.2.2"



sphinx-click = "^3.1.0"
Pygments = "^2.12.0"
types-pkg-resources = "^0.1.2"
types-requests = "^2.28.11"
types-attrs = "^19.1.0"
sphinx-rtd-dark-mode = "^1.2.4"
Jinja2 = "^3.0.0"

[tool.poetry.scripts]
locatieserver = "locatieserver.__main__:main"

[tool.black]
line-length = 120

[tool.mypy]
strict = false
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
ignore_missing_imports = true

[tool.isort]
multi_line_output=3
include_trailing_comma=true
balanced_wrapping=true
line_length=120

[tool.coverage.paths]
source = ["locatieserver", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["locatieserver"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
